#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=20gb,walltime=02:00:00
#PBS -N bl.forward

#SBATCH --ntasks-per-node=1
#SBATCH --mem=20G
#SBATCH --time=02:00:00

set -e
set -x

singularity exec \
  docker://aunnikri642/app-freesurfer-mne-source-recon \
  python3 main.py
